//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bengala.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bengala.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;mismatched tree node: &apos;{0}&apos; expecting &apos;{1}&apos;&quot;.
        /// </summary>
        internal static string AntlrDesconocida_1 {
            get {
                return ResourceManager.GetString("AntlrDesconocida_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;mismatched input &apos;{0}&apos; expecting set &apos;{1}&apos;&quot;.
        /// </summary>
        internal static string AntlrDesconocida_2 {
            get {
                return ResourceManager.GetString("AntlrDesconocida_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;rule {0} failed predicate: { {1} }?&quot;.
        /// </summary>
        internal static string AntlrDesconocida_3 {
            get {
                return ResourceManager.GetString("AntlrDesconocida_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;La lista de declaraciones requiere, al menos, una declaración válida&quot;.
        /// </summary>
        internal static string AntlrLetDeclEmpty {
            get {
                return ResourceManager.GetString("AntlrLetDeclEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Falta algún token.&quot;.
        /// </summary>
        internal static string AntlrMissing {
            get {
                return ResourceManager.GetString("AntlrMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;El token &apos;{0}&apos; no es válido en este contexto&quot;.
        /// </summary>
        internal static string AntlrNoMatch_1 {
            get {
                return ResourceManager.GetString("AntlrNoMatch_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;El token &apos;{0}&apos; no es válido, en este contexto se esperaba un &apos;{1}&apos;&quot;.
        /// </summary>
        internal static string AntlrNoMatch_2 {
            get {
                return ResourceManager.GetString("AntlrNoMatch_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;En este contexto se esperaba un &apos;{0}&apos;&quot;.
        /// </summary>
        internal static string AntlrNoMatch_3 {
            get {
                return ResourceManager.GetString("AntlrNoMatch_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;El token &apos;{0}&apos; es inesperado&quot;.
        /// </summary>
        internal static string AntlrUnexpect_1 {
            get {
                return ResourceManager.GetString("AntlrUnexpect_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Se esperaba el token &apos;{0}&apos; en lugar de &apos;{1}&apos;&quot;.
        /// </summary>
        internal static string AntlrUnexpect_2 {
            get {
                return ResourceManager.GetString("AntlrUnexpect_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;La expresión que indiza un array tiene que ser de tipo &apos;int&apos;.&quot;.
        /// </summary>
        internal static string ArrayIndex {
            get {
                return ResourceManager.GetString("ArrayIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;El &apos;break&apos; tiene que estar dentro de algún ciclo.&quot;.
        /// </summary>
        internal static string Break {
            get {
                return ResourceManager.GetString("Break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;La expresión que inicializa a la variable de iteración &apos;{0}&apos; tiene que ser de tipo &apos;int&apos;.&quot;.
        /// </summary>
        internal static string ForInit {
            get {
                return ResourceManager.GetString("ForInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;La condición de parada de la variable de iteración &apos;{0}&apos; tiene que ser de tipo &apos;int&apos;.&quot;.
        /// </summary>
        internal static string ForStop {
            get {
                return ResourceManager.GetString("ForStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;La función &apos;{0}&apos; ya está definida.&quot;.
        /// </summary>
        internal static string FuncDecl {
            get {
                return ResourceManager.GetString("FuncDecl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;El parámetro &apos;{0}&apos; de la función &apos;{1}&apos; ya existe.&quot;.
        /// </summary>
        internal static string FuncDeclParams {
            get {
                return ResourceManager.GetString("FuncDeclParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;En la función &apos;{0}&apos; no todos los caminos retornan valor.&quot;.
        /// </summary>
        internal static string FuncDeclRet {
            get {
                return ResourceManager.GetString("FuncDeclRet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;La función &apos;{0}&apos; recibe parámetros no válidos.&quot;.
        /// </summary>
        internal static string FuncParams {
            get {
                return ResourceManager.GetString("FuncParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;No existe sobrecarga de la función &apos;{0}&apos; con &apos;{1}&apos; parámetros.&quot;.
        /// </summary>
        internal static string FuncParamsCount {
            get {
                return ResourceManager.GetString("FuncParamsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;La función &apos;{0}&apos; no existe.&quot;.
        /// </summary>
        internal static string FuncUndecl {
            get {
                return ResourceManager.GetString("FuncUndecl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;La variable &apos;{0}&apos; oculta a otra variable.&quot;.
        /// </summary>
        internal static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;La expresión condicional tiene que ser de tipo &apos;int&apos;.&quot;.
        /// </summary>
        internal static string IfCond {
            get {
                return ResourceManager.GetString("IfCond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Solo los array pueden ser indizados.&quot;.
        /// </summary>
        internal static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;El tipo de la variable &apos;{0}&apos; no se puede inferir.&quot;.
        /// </summary>
        internal static string InferType {
            get {
                return ResourceManager.GetString("InferType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;El tipo &apos;{0}&apos; no es válido.&quot;.
        /// </summary>
        internal static string InvalidRet {
            get {
                return ResourceManager.GetString("InvalidRet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;El tipo &apos;{0}&apos; no conforma con el tipo &apos;{1}&apos;.&quot;.
        /// </summary>
        internal static string Match {
            get {
                return ResourceManager.GetString("Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Expresiones de tipo &apos;{0}&apos; no pueden ser negadas&quot;.
        /// </summary>
        internal static string NegExp {
            get {
                return ResourceManager.GetString("NegExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;El token &apos;{0}&apos; no es válido&quot;.
        /// </summary>
        internal static string ProdUndecl_1 {
            get {
                return ResourceManager.GetString("ProdUndecl_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;El token &apos;{0}&apos; no es válido, quizás &apos;{1}&apos;&quot;.
        /// </summary>
        internal static string ProdUndecl_2 {
            get {
                return ResourceManager.GetString("ProdUndecl_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;La expresión no denota un record.&quot;.
        /// </summary>
        internal static string RecAccess {
            get {
                return ResourceManager.GetString("RecAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;El campo &apos;{0}&apos; del tipo &apos;{1}&apos; ya existe.&quot;.
        /// </summary>
        internal static string RecDecl {
            get {
                return ResourceManager.GetString("RecDecl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;El tipo &apos;{0}&apos; no tiene ningún campo &apos;{1}&apos;.&quot;.
        /// </summary>
        internal static string RecField {
            get {
                return ResourceManager.GetString("RecField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;El operador &apos;{0}&apos; no puede ser aplicado a operandos de tipo &apos;{1}&apos; y &apos;{2}&apos;.&quot;.
        /// </summary>
        internal static string SupportOp {
            get {
                return ResourceManager.GetString("SupportOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;El tipo &apos;{0}&apos; ya existe.&quot;.
        /// </summary>
        internal static string TypeDecl {
            get {
                return ResourceManager.GetString("TypeDecl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;El tipo &apos;{0}&apos; no existe.&quot;.
        /// </summary>
        internal static string TypeUndecl {
            get {
                return ResourceManager.GetString("TypeUndecl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;La variable &apos;{0}&apos; ya está declarada en este scope.&quot;.
        /// </summary>
        internal static string VarDecl {
            get {
                return ResourceManager.GetString("VarDecl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;La variable &apos;{0}&apos; no está declarada.&quot;.
        /// </summary>
        internal static string VarUndecl {
            get {
                return ResourceManager.GetString("VarUndecl", resourceCulture);
            }
        }
    }
}
